title: "Koept Catalogue"
theme: riggraz/no-style-please
description: "A listing of the original inept catalogue"
baseurl: "/catalogue" # adjust to your repository name
url: "https://oscott.github.io" # your GitHub Pages URL
permalink: /:title/

# Optional, but handy for organizing posts:
collections:
  catalog:
    output: true
    permalink: /:title/

# Exclude unnecessary files:
exclude:
  - Gemfile
  - Gemfile.lock
